---
title: "About me"
author: "Andrew Bengsen"
date: "17/05/2020"
output: 
  md_document:
    variant: markdown_github
---

## Andrew Bengsen  
### Wildlife Ecologist  

My work is all about helping people to protect natural resources, agricultural production and human health through the effective management of overabundant mammal populations.  

Poor or ineffective management wastes opportunity, time, money, energy, animal lives, and social licence. Often, small changes to established practice can make big differences to outcomes. This is what gets me out of bed in the morning (often *waaaay* too early).   

I use robust study design, powerful data analysis, and strong logical and critcal thinking to provide reliable information in a way that empowers people to make good, science-based wildlife management decisions and get the results they need.  

My current research uses field- and desk-based studies to answer questions like:  

  - how does recreational hunting contribute to the management of wild deer, feral pigs and other problem species?
  - how valid are the assumptions about deer spatial ecology that underpin current deer and feral pig management?
  - how can we develop and improve methods to estimate the states and dynamics of mammal populations?
  - how much effort do we need to invest to get useful outcomes from deer and pig management operations?

I also enjoy working with human behaviour researchers to understand how we can remove barriers to effective management and provide resources and conditions that promote great outcomes.  

I love challenging assumptions and I'm always happy to have my prior beliefs updated.  

[MY PUBLICATIONS](https://andrewbengsen.github.io/Publications.html)
[RECENT PRESENTATIONS](https://andrewbengsen.github.io/Presentations.html)

