---
title: "Presentations"
author: "Andrew Bengsen"
date: "26/05/2020"
output: 
  md_document:
    variant: markdown_github
---

[back](https://andrewbengsen.github.io/)

## Recent presentations  

  - Bengsen, A. J. (2023) [Wildlife Disease Surveillance and Modelling](Media/BENGSEN_ISB_seminar_series_disease_project_outline_2023-03.pdf). NSW DPI Invasive Species Biosecurity seminar series, March 2023.
  - Bengsen, A. J. (2022) [A Series of Porcine-ite Events](https://www.slideshare.net/AndrewBengsen/balanced-researcher-program-presentation-a-bengsenpptx). Centre for Invasive Species Solutions Balanced Researcher / Balanced Scientist Program event, Canberra, September 2022.
  - Bengsen, A. J. (2022) [Spatial Behaviour of Fallow Deer in NSW](Media/BENGSEN_2022_deer-collaring_deer-masterclass.pdf). NSW DPI Deer Management Masterclass, Tamworth, August 2022.
  - Bengsen, A. J. (2022) [Aerial Deer Survey](Media/BENGSEN_2022_Aerial-survey_deer-masterclass.pdf). NSW DPI Deer Management Masterclass, Tamworth, August 2022.
  - Bengsen, A. J., Forsyth, D. M., Pople, A., Brennan, M., Amos, M., Leeson, M., Cox, T., Gray, R., Orgill, O., Hampton, J. O., Crittle, T., Haebich, K. (2022) [Costs and Effectiveness of Aerial Shooting Operations](Media/BENGSEN_2022_aerial-shoot_deer-masterclass.pdf). NSW DPI Deer Management Masterclass, Tamworth, August 2022.
  - Bengsen, A. J., Forsyth, D. M., Pople, A., Brennan, M., Amos, M., Leeson, M., Cox, T., Gray, R., Orgill, O., Hampton, J. O., Crittle, T., Haebich, K. (2022) [Costs and Effectiveness of Aerial Shooting Operations](Media/BENGSEN_HunterLLS_aerial-shoot-deer_2022-05.pdf). Presentation to Hunter Local Land Services, May 2022.
  - Bengsen, A. J., Forsyth, D. M., Pople, A., Brennan, M., Amos, M., Leeson, M., Cox, T., Gray, R., Orgill, O., Hampton, J. O., Crittle, T., Haebich, K. (2021) [Functional Response and the Effort-Outcomes Relationship for Aerial Shooting of Deer](https://www.slideshare.net/AndrewBengsen/aerialshootdeerawms2021pptx). Australasian Wildlife Management Society Conference, online.
  
  - Bengsen, A. J. 2021 [Practicalities of camera trapping to detect and count feral pigs](Media/BENGSEN_NFPAP_practicalities-of-camera-traps-for-pigs_2021-12.pdf). National Feral Pig Action Plan Stakeholder Forum.

  - Bengsen, A. J., Forsyth, D. M., Ramsey, D. (2019) [Camera trap methods for estimating densities of deer and poorly-marked species](Media/BENGSEN_AWMS_2019_Deer_SMR.pdf). Australasian Wildlife Management Society Conference, Darwin.
  - Bengsen, A. J., Forsyth, D. M., Ramsey, D. (2019) [Camera trap survey methods for estimating changes in deer density and occurrence](https://vpmsymposium.com.au/base/wp-content/uploads/presentations2018/Andrew%20Bengsen.pdf). NSW Vertebrate Pest Symposium, Coffs Harbour.
  